### ISSUE TITLE
The type or namespace name 'GodotUtilities' could not be found

### ISSUE THREAD

**Issue by valkyrienyanko** [godotmancer/SampleGodotCSharpProject#1]
![Capture](https://user-images.githubusercontent.com/6277739/220746113-906cacc6-61e7-4752-901d-34ec92bf56ad.PNG)

## I am having troubles figuring out how to include GodotUtilities namespace properly.

![Capture](https://user-images.githubusercontent.com/6277739/220744725-452bbecb-7319-4334-ba47-c2220979e273.PNG)

I do not know what "soft-link" means.

Here's what I've tried.

I have added `<add key="local" value="packages/offline" />` to the `nuget.config` file and put the latest Godot Utilities release `.nupkg` in `./packages/offline`.

![Capture](https://user-images.githubusercontent.com/6277739/220745893-becb2221-8691-471b-a7f5-6e0f3181403a.PNG)

![Capture](https://user-images.githubusercontent.com/6277739/220746029-7bb686ab-f25a-41eb-b10f-2bf72519c04d.PNG)

I then tried building the Godot game but nothing changed.

**Comment by godotmancer** [comment]
Hi @valkyrienyanko a soft link is a *nix term ("`ln -s /home/user/somefolder .`"), I guess this isn't ideal especially if you are using some other OS. Let me check in the GodotUtilities folder, been contemplating this and I think it makes sense as I will try to keep up with the latest Firebelley commits.

**Comment by godotmancer** [comment]
Updated the project to include GodotUtilities folder.
